# Generated by Django 2.2 on 2019-04-11 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=192)),
                ('student_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.PositiveIntegerField()),
                ('project_id', models.PositiveIntegerField()),
                ('category_id', models.PositiveIntegerField()),
                ('project_name', models.TextField()),
                ('level', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('is_group', models.BooleanField()),
                ('score', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=192)),
                ('address', models.CharField(max_length=192)),
                ('school_id', models.PositiveIntegerField()),
                ('students_attending', models.PositiveIntegerField()),
                ('chaperones_attending', models.PositiveIntegerField()),
                ('teachers_attending', models.PositiveIntegerField()),
                ('drivers_attending', models.PositiveIntegerField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=15)),
                ('contact_name', models.CharField(max_length=192)),
                ('contact_email', models.CharField(max_length=192)),
                ('contact_primary_phone', models.CharField(max_length=64)),
                ('contact_alternate_phone', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_first', models.CharField(max_length=192)),
                ('name_last', models.CharField(max_length=192)),
                ('level', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('school_id', models.PositiveIntegerField()),
                ('is_testing', models.BooleanField()),
                ('student_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.PositiveIntegerField()),
                ('student_id', models.PositiveIntegerField()),
            ],
        ),
    ]
