# Generated by Django 2.2 on 2019-04-11 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='student_id',
            new_name='category_id',
        ),
    ]
