# Generated by Django 2.2 on 2019-04-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190411_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='school',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='school',
            name='contact_alternate_phone',
            field=models.CharField(blank=True, max_length=66),
        ),
        migrations.AlterField(
            model_name='school',
            name='students_attending',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
