# Generated by Django 2.2 on 2019-04-24 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190424_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_project',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='student_project',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student', verbose_name='Student'),
        ),
    ]
