# Generated by Django 2.2 on 2019-04-24 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190424_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='school_id',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='school_id',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='student_project',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='student_project',
            old_name='student_id',
            new_name='student',
        ),
    ]
