# Generated by Django 2.2 on 2019-04-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190424_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='contact_alternate_phone',
            field=models.CharField(max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='students_attending',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
