# Generated by Django 2.2 on 2019-04-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190425_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='front_end_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='score',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='contact_alternate_phone',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='students_attending',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
