# Generated by Django 2.2 on 2019-07-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_project_scoring_judge'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='judges_comments',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
